---
title: "aov_results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstatix)
library(scales)

preprocessTablas1 <- function(root, nombreTabla) {
  
    # Getting data ready
  rootTabla <- paste0(root, nombreTabla)
  
  tabla <- read.csv(rootTabla)
  
  
  # Make factors of categorical features
  
  tabla$Endulzante <- factor(tabla$Endulzante, levels = c("SA", "ST", "SU"))
  tabla$Sexo <- factor(tabla$Sexo, levels = c("HOMBRE", "MUJER"))
  tabla$Tiempo <- factor(tabla$Tiempo, levels = c("0", "Final"))
  tabla$numVol <- factor(tabla$numVol)
  
  for (i in seq(1:nrow(tabla))){
    if (tabla$Tiempo[i] == "0"){
      tabla$Peso[i] = tabla$Peso.inicial[i]
      tabla$IMC[i] = tabla$IMC.Inicial[i]
      tabla$Grasa[i] = tabla$Grasa.inicial[i]
      tabla$IRCV[i] = tabla$IRCV.inicial[i]
      tabla$Bpmin[i] = tabla$Bpmin.inicial[i]
      tabla$Bpmax[i] = tabla$Bpmax.inicial[i]
      tabla$Frec[i] = tabla$Frec.inicial[i]
      
    }
    
    else if (tabla$Tiempo[i] == "Final"){
      tabla$Peso[i] = tabla$Peso.final[i]
      tabla$IMC[i] = tabla$IMC.Final[i]
      tabla$Grasa[i] = tabla$Grasa.final[i]
      tabla$IRCV[i] = tabla$IRCV.Final[i]
      tabla$Bpmin[i] = tabla$Bpmin.final[i]
      tabla$Bpmax[i] = tabla$Bpmax.final[i]
      tabla$Frec[i] = tabla$Frec.final[i]
    }
    
    
  }
  
  # Removing of trivial redundant and useless features 
  
  set.A <- subset(tabla, select =-c(X.1, X, Peso.inicial, Peso.final, Delta.Peso, Talla, IMC.Inicial, IMC.Final, 
                                    Delta.IMC, Grasa.inicial, Grasa.final, Delta.Grasa, IRCV.Final, IRCV.inicial, 
                                    Bpmin.final, Bpmin.inicial, Bpmax.final, Bpmax.inicial, Frec.final, Frec.inicial))
  
  # Only numerical features
  
  set.A_num <- subset(set.A, select=-c(Endulzante, Sexo, Tiempo, numVol))
  
  #Rescaling, can use "set.A_rescaled <- scale(set.A_num)" too
  
  set.A_rescaled <- set.A_num %>% mutate_each_(list(~rescale(.) %>% as.vector), 
                                               vars = colnames(set.A_num))
  
  set.A_factors <- cbind(set.A_rescaled, Endulzante = set.A$Endulzante, 
                         Tiempo = set.A$Tiempo, Sexo = set.A$Sexo, numVol = set.A$numVol)
  
  

  return(tablaFactors = set.A_factors)
}


```


```{r lectura tablas, include=FALSE}


orinaFlav <- preprocessTablas1("data/", "tablaOrinaFlav.csv")
orinaAnt <- preprocessTablas1("data/", "tablaorinaAnt.csv")
plasmaAnt <- preprocessTablas1("data/", "tablaplasmaAnt.csv")
plasmaFlav <- preprocessTablas1("data/", "tablaplasmaFlav.csv")




```


```{r anova, include=FALSE}
aov_test <- function(tabla, variable){
  
  tablaVar <- tabla %>% select(numVol, Endulzante, Sexo, Tiempo, variable)
  
  tablaVar <- tablaVar[!tablaVar[,variable] %in% boxplot.stats(tablaVar[,variable])$out,]
    
  res.aov <- anova_test(data = tablaVar, dv=variable, wid=numVol, 
                         between = c(Sexo, Endulzante), within= Tiempo)

  tablaAnova <- get_anova_table(res.aov, correction = "auto")
  
  print(tablaAnova)
}

aov_loop <- function(tabla){
   
  message(paste("Tabla analizada: ", deparse(substitute(tabla))))
  for (i in seq(1,ncol(tabla))){
  
    if (is.numeric(tabla[,i])){
        message(paste("Variable analizada: ", names(tabla)[i]))
        aov_test(tabla,
           names(tabla)[i])
    }
  
  
  }
}


```

```{r anova_exec}


aov_loop(orinaFlav)
aov_loop(orinaAnt)
aov_loop(plasmaAnt)
```


```{r pairwise, include= FALSE}

pairwiseTTest <- function(tabla){
  
  counts <- data.frame(table(tabla$numVol))
  
  tabla <- tabla[tabla$numVol %in% counts$Var1[counts$Freq > 1],]
  
  for (i in colnames(tabla)){
    
    if (is.numeric(tabla[,i])){
      
      
      message(paste("Variable analizada: ", i))
      
      message(paste("Comparaciones Tiempo ", i)) 
      
      print(pairwise_t_test(data = tabla , formula = as.formula(paste(sym(i),"~ Tiempo")),
                            paired = T, p.adjust.method = "bonferroni")
            %>% dplyr::select(-df, -statistic))
      
      tablaGr <- group_by(tabla, Endulzante, Sexo)
      
      message(paste("Comparaciones Tiempo-Endulzante-Sexo ", i))
      
      print(pairwise_t_test(data = tablaGr , formula = as.formula(paste(sym(i),"~ Tiempo")),
                            paired = T, p.adjust.method = "bonferroni") %>% dplyr::select(-df, -statistic))
      
      
      tablaGr <- group_by(tabla, Endulzante)
      
      message(paste("Comparaciones Tiempo-Endulzante", i))
      
      print(pairwise_t_test(data = tablaGr , formula = as.formula(paste(sym(i),"~ Tiempo")),
                            paired = T, p.adjust.method = "bonferroni") %>% dplyr::select(-df, -statistic))
      
      
      tablaGr <- group_by(tabla, Sexo)
      
      message(paste("Comparaciones Tiempo-Sexo", i))
      
      print(pairwise_t_test(data = tablaGr , formula = as.formula(paste(sym(i),"~ Tiempo")),
                            paired = T, p.adjust.method = "bonferroni") %>% dplyr::select(-df, -statistic))
    }
  }
}



```


```{r pairwise_exec}
pairwiseTTest(orinaFlav)
pairwiseTTest(orinaAnt)
pairwiseTTest(plasmaAnt)

```

