---
title: "Untitled"
author: "DHdez"
date: "13/12/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(scales)
library(stargazer)
library(rstatix)
source("../scripts/preprocess.R")
source("../scripts/anova.R")

```

```{r reading and merging, include=FALSE}

orinaFlav <- preprocessTables("../data/", "tablaOrinaFlav.csv")
orinaAnt <- preprocessTables("../data/", "tablaorinaAnt.csv")
plasmaAnt <- preprocessTables("../data/", "tablaplasmaAnt.csv")
plasmaFlav <- preprocessTables("../data/", "tablaplasmaFlav.csv")


tabla1 <- orinaFlav$tablaFactors %>% 
          select(-c(Peso, IMC, Grasa, IRCV, Bpmin, Bpmax, Frec))

tabla2 <- orinaAnt$tablaFactors %>% 
          select(-c(Peso, IMC, Grasa, IRCV, Bpmin, Bpmax, Frec, Endulzante, 
                    Sexo, Tiempo))

tabla3 <- plasmaAnt$tablaFactors %>% 
          select(-c(Peso, IMC, Grasa, IRCV, Bpmin, Bpmax, Frec, Endulzante, 
                    Sexo, Tiempo))

tabla_antro <- plasmaFlav$tablaFactors %>% 
               select(c(numVol, Peso, IMC, Grasa, IRCV, Bpmin, Bpmax, Frec)) 

tabla_merge <- na.omit(full_join( full_join( full_join(
               tabla_antro %>% group_by(numVol) %>% mutate(id = row_number()),
               tabla1 %>% group_by(numVol) %>% mutate(id = row_number()), by = c("numVol", "id")), 
               tabla2 %>% group_by(numVol) %>% mutate(id = row_number()), by = c("numVol", "id")),
               tabla3 %>% group_by(numVol) %>% mutate(id = row_number()), by = c("numVol", "id")) )


counts <- data.frame(table(tabla_merge$numVol))

tabla_mergeDupl <- tabla_merge[tabla_merge$numVol %in% counts$Var1[counts$Freq > 1],]

```

```{r aov}

aov_loop(tabla_mergeDupl)

```




