---
title: "1stAnalysis"
author: "DHdez"
date: "18/10/2022"
output: html_document
---

### Los análisi


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
library(psych)
library(modeest)
library(caret)
library(rstatix) 
library(AppliedPredictiveModeling)
library(reshape2)
library(clValid)
library(mclust)
library(factoextra)
library(ggpubr)
library(simputation)
library(cluster)
library(Boruta)
library(mlbench)
library(caret)
library(randomForest)
library(gridExtra)
library(RColorBrewer)

readingFillingGrouping <- function(tablaPath){
    
    tabla <- read.csv(tablaPath, sep = ";", dec = ".")
    
    if (tablaPath == "../../effectsSexIntakers/data/chronicUrineFlav.csv"){
      tabla <- read.csv(tablaPath, sep = ";", dec = ",")
    }
    
    # remove raw data from spectometry
    
    for (i in colnames(tabla)){
      if(substr(i, nchar(i), nchar(i)) != "1" & i != "grouping"){
        tabla[,i] <- NULL
      }
    }
    
    # adding sweetener
    
    for (i in seq(1, nrow(tabla))){
      
      if (grepl(pattern = "A", x = tabla$grouping[i])){
        tabla$Sweetener[i] <- "ST"
      }
      
      else if (grepl(pattern = "B", x = tabla$grouping[i])){
        tabla$Sweetener[i] <- "SU"
      }
      
      else if (grepl(pattern = "C", x = tabla$grouping[i])){
        tabla$Sweetener[i] <- "SA"
      }
      
      # adding numVol
      
      if (length(tabla$grouping[i]) == 4){
        tabla$numVol[i] <- as.numeric(substr(tabla$grouping[i],0,1))
        if (tabla$Sweetener[i] == "SU"){
          tabla$numVol[i] = tabla$numVol[i] + 50
        }
        
        else if (tabla$Sweetener[i] == "SA"){
          tabla$numVol[i] = tabla$numVol[i] + 100
        }
        
      }
      
      else {
        tabla$numVol[i] <- as.numeric(substr(tabla$grouping[i],0,2))
        
        if (tabla$Sweetener[i] == "SU"){
          tabla$numVol[i] = tabla$numVol[i] + 50
        }
        
        else if (tabla$Sweetener[i] == "SA"){
          tabla$numVol[i] = tabla$numVol[i] + 100
        }
        
      }
      
      if (grepl(pattern = "F", x = tabla$grouping[i])){
        tabla$Time[i] <- "Final"
      }
      else if (grepl(pattern = "([A-C])0", x = tabla$grouping[i])){
        tabla$Time[i] <- "Initial"
        
      }
      
      
    }    
    
    tableSex <- read.csv("../../effectsSexIntakers/data/chronicSexVolunteers.csv", sep = ";", dec = ",")
    
    tabla <- merge(tabla, tableSex, by = "numVol")
    
    tabla$Sex[tabla$Sex == "HOMBRE"] <- "MAN"
    tabla$Sex[tabla$Sex == "MUJER"] <- "WOMAN"
    
    
    
    return(tabla)
    
  }
  
normalizingNumeric <- function(tableComplete) {
  
  for (i in colnames(tableComplete)){
    
    if (is.numeric(tableComplete[,i]) && i != "numVol"){
      
      tableComplete[,i] <- scales::rescale(tableComplete[,i])
      
    }
    
  }
  return (tableComplete)    
}

factoringImputating <- function(tableNorm){
  
  tableNorm$Sweetener <- factor(tableNorm$Sweetener) 
  tableNorm$Sex <- factor(tableNorm$Sex)
  tableNorm$Time <- factor(tableNorm$Time)
  
  return(tableNorm)   
  
}


estadisticosDescriptivos <- function (tabla) {
  
  #Encabezados de cada estadístico como un vector
  nombres <- c("Mínimo", "Q1", "Media", "Media recortada", "Mediana", "Moda",
               "Varianza", "Desviación Estándar", "Q3", "Máximo", "Simetría", "Curtosis")
  
  descr2 <- data.frame(matrix(ncol = length(nombres), nrow = 0))
  
  
  for (i in colnames(tabla)) {
    if (is.numeric(tabla[, i]) & i != "numVol"){
      
      min <- min(tabla[, i], na.rm = TRUE)
      q1 <- quantile(tabla[, i], probs = 0.25, na.rm = TRUE)
      media <- mean.default(tabla[, i], na.rm = TRUE)
      media_rec <- mean.default(tabla[, i], trim = 0.025, na.rm = TRUE)
      mediana <- median.default(tabla[, i], na.rm = TRUE)
      moda <- mfv1(tabla[, i])
      var <- var(tabla[, i], na.rm = TRUE)
      desvest <- sd(tabla[, i], na.rm = TRUE)
      q3 <- quantile(tabla[, i], probs = 0.75, na.rm = TRUE)
      max <- max(tabla[, i], na.rm = TRUE)
      s <- skew(tabla[, i])
      c <- kurtosi(tabla[, i])
      
      
      #Valores de estadísticos como vector
      descriptivos <- as.numeric(c(min, q1, media, media_rec, mediana, moda,
                                   var, desvest, q3, max, s, c))
      
      descr2 <- as.data.frame(rbind(descr2, descriptivos))
      
      
      colnames(descr2) <- nombres
      
      
    }
    
    
    
  }
  
  rownames(descr2) <- colnames(tabla)[!(colnames(tabla) %in% c("numVol", "grouping","Sex", "Time", "Sweetener"))] 
  
  return (descr2)
  
}

# timing the features

timingCleanFeatures <- function(tabla, pathToTable){
  

  if (pathToTable == "data/chronicPlasmAnt.csv"){
    rename(tabla, CA = Caffeic.Acid..CA..1, CA.G = CA.Gluc.1, 
           CA.S = CA.Sulfate.1, Total.CA = TOTAL.CA.1,
           DHPAA = X3.4.Dihidroxiphenilacetic.acid..DHPAA..1, 
           DHPAA.G = DHPAA.Gluc.1, 
           DHPAA.GG = DHPAA.di.Gluc.1,
           DHPAA.GS = DHPAA.Gluc.sulfate.1, 
           DHPAA.SS = DHPAA.di.Sulfate.1, 
           Total.DHPAA = TOTAL.DHPAA.1,
           TFA.G = TFA.Gluc.1, 
           TFA.S = TFA.Sulfate.1, Total.TFA = TOTAL.TFA.1, 
           VA = Vanillic.Acid..VA..1,
           VA.GG = VA.GG.1, 
           VA.S = VA.Sulfate.1, 
           VA.GS = VA.Gluc.sulfate.1, 
           VA.SS = VA.di.sulfate.1, Total.VA = Total.VA.1)
    
  }
  
  else if(pathToTable == "data/chronicPlasmFlav.csv"){
    rename(tabla, E = Eriodictiol..E..1, 
           E.S = ES.1 , 
           Total.E = TOTAL.E.1, 
           HE.G = HE.G.1, N.G = NG.1)
  }
  
  else if(pathToTable == "data/chronicUrineFlav.csv"){
    rename(tabla, 
           E = Eriodyctiol..E..1, E.G = ES.1, E.S = ES.1 , Total.E = TOTAL.E.1, 
           HE = HE.1, HE.G = HE.G.1, 
           HE.GG = HE.GG.1, Total.HE = TOTAL.HE.1, 
           N = Naringenine..N..1, N.G = NG.1, N.GG = NGG.1, N.S = NS.1, 
           Total.N = TOTAL.N.1)
  }
  
  else if (pathToTable == "data/chronicUrineAnt.csv"){
    rename(tabla, 
           CA = Caffeic.acid..CA..1, 
           CA.G= CA.Gluc.1, CA.S = CA.Sulfate.1, 
           CA.GS = CA.Gluc.sulfate.1, Total.CA = TOTAL.CA.1,
           DHPAA = X3.4...Dihidroxiphenilacetic.acid..DHPAA..1, 
           DHPAA.G = DHPAA.Gluc.1, DHPAA.GG = DHPAA.di.Gluc.1, 
           DHPAA.GS = DHPAA.Gluc.sulfate.1, 
           DHPAA.SS = DHPAA.di.Sulfate.1, Total.DHPAA = TOTAL.DHPAA.1, 
           TFA.G = TFA.Gluc.1, TFA.S = TFA.Sulfate.1, Total.TFA = TOTAL.TFA.1, 
           VA = Vanillic.Acid..VA..1, VA.GG = VA.GG.1, 
           VA.GS = VA.Gluc.sulfate.1, VA.SS = VA.di.sulfate.1, Total.VA = Total.VA.1)
  }
  
  
  # return(tabla)
}

# Función para realizar la anova de tres vías sobre una variable
# Imprime por pantalla el resultado

aov_test <- function(tabla, variable){
  
  tablaVar <- tabla %>% select(numVol, Sweetener, Sex, Time, variable)
  
  # tablaVar <- tablaVar[!tablaVar[[5]] %in% boxplot.stats(tablaVar[[5]])$out,]
  
  res.aov <- anova_test(data = ungroup(tablaVar), dv=variable, wid=numVol, 
                        between = c(Sex, Sweetener), within= Time)
  
  tablaAnova <- get_anova_table(res.aov, correction = "auto")
  
  print(tablaAnova)
}

# Función para hacer en bucle el análisis anova a lo largo de una tabla

aov_loop <- function(tabla, varsRemoved){
  
  
  # remover no duplicados
  if (deparse(substitute(tabla)) %in% c("urineAnt", "urineFlav")){
    counts <- data.frame(table(tabla$numVol))
    tabla <- tabla[tabla$numVol %in% counts$Var1[counts$Freq > 1],]
  }
  
  message(paste("Tabla analizada: ", deparse(substitute(tabla))))
  for (i in colnames(tabla)[-1]){
    
    if (is.numeric(tabla[,i]) && !(i %in% varsRemoved)){
      
      message(paste("Variable analizada: ", i))
      aov_test(tabla,i)
    }
    
    
  }
}

anovaTests <- function(tabla, varsRemoved) {
  
  aov_loop(tabla, varsRemoved)
  pairwiseTTest(tabla, varsRemoved)
  
  
}

boxplotBias <- function(vars, table1.0, factore, removeOutliers = F, titlePLot, x_label ){
  
  # reading table
  
  table1.1 <- table1.0 %>% select (all_of(vars), Time, Sex, Sweetener, -c(numVol, grouping))
  
  
  
  if (removeOutliers){
    
    for (i in colnames(table1.1)) {
      
      if (is.numeric(table1.1[,i])){
        
        table1.1 <- table1.1[!table1.1[, i] %in% boxplot.stats(table1.1[,i])$out,]
        
      }
    } 
    
    # return(table1.1)
    
  }
  
  
  # long table format
  
  table1.2 <- melt(table1.1, id = c("Time", "Sex", "Sweetener"))
  
  # plot factors
  
  bxp <- function(longTable, factore, x_label){
    
    
    
    if (factore == "Time") {
      
      ggplot(longTable, aes(factor(variable, 
                                   level = unique(longTable$variable)),as.numeric(value), 
                            fill=factor(longTable[,factore], 
                                        levels = c("Initial", "Final")))) +
        geom_boxplot()+
        ggtitle(titlePLot)+
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+
        labs(y = "standarized value", x = x_label, fill = "Time")
      
    }
    
    else if (factore == "Sex") {
      ggplot(longTable, aes(factor(variable, 
                                   level = unique(longTable$variable)),as.numeric(value), 
                            fill=factor(longTable[,factore]))) +
        geom_boxplot()+
        ggtitle(paste(titlePLot))+
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+
        labs(y = "standarized value", x = x_label, fill = "Sex")+
        scale_fill_brewer(palette = "Reds")+  
        facet_wrap(~factor(Time, levels = c("Initial", "Final")))
      
      
    }
    
    else if (factore == "Sweetener"){
      ggplot(longTable, aes(factor(variable, 
                                   level = unique(longTable$variable)),as.numeric(value), 
                            fill=factor(longTable[,factore])), colour = "Sweetener") +
        geom_boxplot()+
        ggtitle(titlePLot)+
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+
        labs(y = "standarized value", x = x_label, fill = "Sweetener")+
        facet_wrap(~factor(Time, levels = c("Initial", "Final")))
      
      
    }
  }
  
  
  bxp(table1.2, factore, x_label)
  
}

pairwiseTTest <- function(tabla, varsRemoved){
  
  
  
  for (i in colnames(tabla)){
    
    if (is.numeric(tabla[,i]) & !(i %in% varsRemoved)){
      
      
      message(paste("Analized variable: ", i))
      
      message(paste("Time comparisons ", i)) 
      
      print(pairwise_t_test(data = tabla , formula = as.formula(paste(sym(i),"~ Time")),
                            paired = T, p.adjust.method = "bonferroni")
            %>% dplyr::select(-df, -statistic))
      
      tablaGr <- group_by(tabla, Sweetener, Sex)
      
      message(paste("Time-Sweetener-Sex comparisons", i))
      
      print(pairwise_t_test(data = tablaGr, formula = as.formula(paste(sym(i),"~ Time")),
                            paired = T, p.adjust.method = "bonferroni") %>% dplyr::select(-df, -statistic))
      
      
      tablaGr <- group_by(tabla, Sweetener)
      
      message(paste("Time-Sweetener comparisons", i))
      
      print(pairwise_t_test(data = tablaGr , formula = as.formula(paste(sym(i),"~ Time")),
                            paired = T, p.adjust.method = "bonferroni") %>% dplyr::select(-df, -statistic))
      
      
      tablaGr <- group_by(tabla, Sex)
      
      message(paste("Time-Sex comparisons", i))
      
      print(pairwise_t_test(data = tablaGr , formula = as.formula(paste(sym(i),"~ Time")),
                            paired = T, p.adjust.method = "bonferroni") %>% dplyr::select(-df, -statistic))
    }
  }
}


main1prepoc <- function(pathToTable, pathtoRealTable){

tabla1.0 <- readingFillingGrouping(pathToTable)
tabla1.1 <- normalizingNumeric(tabla1.0)
tabla1.2 <- factoringImputating(tabla1.1)
#tabla1.2_stats <- estadisticosDescriptivos(urAnt1.2)
tabla1.3 <- timingCleanFeatures(tabla1.2, pathtoRealTable)

return (tabla1.3)

}

```

## Comienza lo weno

```{r lectura tablas}
plasmAnt <- main1prepoc("../../effectsSexIntakers/data/chronicPlasmAnt.csv", "data/chronicPlasmAnt.csv")
plasmFlav <- main1prepoc("../../effectsSexIntakers/data/chronicPlasmFlav.csv", "data/chronicPlasmFlav.csv")
urineFlav <- main1prepoc("../../effectsSexIntakers/data/chronicUrineFlav.csv", "data/chronicUrineFlav.csv")
urineAnt <- main1prepoc("../../effectsSexIntakers/data/chronicUrineAnt.csv", "data/chronicUrineAnt.csv")
```

## Descriptive

```{r descriptive}

write.csv(estadisticosDescriptivos(plasmAntImp), "../supplementary/descriptivosPlasmAnt")
write.csv(estadisticosDescriptivos(plasmFlavImp), "../supplementary/descriptivosFlavAnt")
```



## Anova Test

```{r test anova}

anovaTests(plasmAnt, varsRemoved = c("VA", "Total.VA"))
anovaTests(plasmFlav, varsRemoved = c("Total.E"))
anovaTests(urineFlav, varsRemoved = NULL)

counts <- data.frame(table(urineAnt$numVol))
urineAnt_nodup <- urineAnt[urineAnt$numVol %in% counts$Var1[counts$Freq > 1],]
#uwu1<- as.tibble(map(urineAnt_nodup, ~sum(is.na(.))))
#urineAntImp <- impute_cart(urineAnt, CA.Gluc + DHPAA.Gluc + Total.DHPAA + TFA.Gluc + TFA.Sulfate + VA ~ Sweetener + Sex + Time)          
anovaTests(urineAnt_nodup, varsRemoved = c("CA.S", "DHPAA.GG", "TFA.di.sulfate.1", "TIFA.Sulfate.1"))

# colnames(urineAnt)
# uwu1<- as.tibble(map(urineAnt, ~sum(is.na(.))))
#CA.Gluc.Sulfate + Total.CA + Total.TFA + Total.VA +

```

# Boxplot bias

```{r boxplot bias}

#Boxplot urine-anthocyanins

boxplotBias(vars = c("DHPAA", "VA", "VA.GS", "Total.VA"), table1.0 = urineAnt_nodup, factore = "Time", removeOutliers = T, titlePLot = "A. Time evolution Anthocyanins-Urine", x_label = "Bioactive Anthocyanins")

boxplotBias(vars = c("CA","DHPAA", "Total.DHPAA", "VA.Gluc.Sulfate"), table1.0 = urineAnt_nodup, factore = "Sex", removeOutliers = T, titlePLot = "B. Sex:Time evolution Anthocyanins-Urine", x_label = "Bioactive Anthocyanins")

boxplotBias(vars = c("CA","DHPAA", "DHPAA.Gluc.Sulfate", "Total.DHPAA", "VA.Gluc.Sulfate"), table1.0 = urineAnt_nodup, factore = "Sweetener", removeOutliers = T, titlePLot = "C. Sweetener:Time evolution Anthocyanins-Urine",  x_label = "Bioactive Anthocyanins")

# Boxplot flavanones urine

boxplotBias(vars = c("HE", "HE.G", "HE.GG", "Total.HE", "NG", "Total.N"), table1.0 = urineFlav, factore = "Time", removeOutliers = F, titlePLot = "A. Time evolution Flavanones-Urine",  x_label = "Bioactive Flavanones")

boxplotBias(vars = c("E","EG.1","ES", "Total.E","HE", "HE.G", "HE.GG", "Total.HE", "NG", "Total.N"), table1.0 = urineFlav, factore = "Sex", removeOutliers = F, titlePLot = "B. Sex:Time evolution Flavanones-Urine",  x_label = "Bioactive Flavanones")

boxplotBias(vars = c("E","EG.1","ES", "Total.E","HE", "HE.G", "HE.GG", "Total.HE", "NG", "Total.N"), table1.0 = urineFlav, factore = "Sweetener", removeOutliers = F, titlePLot = "C. Sweetener:Time evolution Flavanones-Urine",  x_label = "Bioactive Flavanones")

#Boxplot anthocyanins plasm

boxplotBias(vars = c("CA",  "CA.Gluc", "Total.CA", "DHPAA","DHPAA.Gluc", "DHPAA.di.Gluc","DHPAA.Gluc.Sulfate", "Total.DHPAA",
                    "Total.TFA", "VA.GG","VA.Sulfate", "VA.Gluc.Sulfate", "VA.di.Sulfate"), table1.0 = plasmAnt, factore =                         "Time", removeOutliers = F, titlePLot = "A. Time evolution Anthocyanins-Plasm",  x_label = "Bioactive Anthocyanins")

boxplotBias(vars = c("CA",  "CA.Gluc", "Total.CA", "DHPAA","DHPAA.Gluc", "DHPAA.di.Gluc","DHPAA.Gluc.Sulfate", 
                     "DHPAA.di.Sulfate","Total.DHPAA","TFA.Sulfate","Total.TFA", "VA.GG","VA.Sulfate", "VA.Gluc.Sulfate"), 
                     table1.0 = plasmAnt, factore ="Sex", removeOutliers = F, titlePLot = "B. Sex:Time evolution Anthocyanins-Plasm",  x_label = "Bioactive Anthocyanins")

boxplotBias(vars = c("CA",  "CA.Gluc", "Total.CA", "DHPAA","DHPAA.Gluc", "DHPAA.di.Gluc","DHPAA.Gluc.Sulfate", 
                     "DHPAA.di.Sulfate","Total.DHPAA","TFA.Gluc","TFA.Sulfate","Total.TFA", "VA.GG","VA.Sulfate", "VA.Gluc.Sulfate", "VA.di.Sulfate"), 
                     table1.0 = plasmAnt, factore ="Sweetener", removeOutliers = F, titlePLot = "C. Sweetener:Time evolution Anthocyanins-Plasm",  x_label = "Bioactive Anthocyanins")



#Boxplot anthocyanins plasm less compounds


boxplotBias(vars = c("CA",  "CA.Gluc", "Total.CA", "DHPAA","DHPAA.Gluc", "DHPAA.di.Gluc","DHPAA.Gluc.Sulfate", "Total.DHPAA",
                    "Total.TFA", "VA.GG","VA.Sulfate", "VA.Gluc.Sulfate", "VA.di.Sulfate"), table1.0 = plasmAnt, factore =                         "Time", removeOutliers = F, titlePLot = "A. Time evolution Anthocyanins-Plasm",  x_label = "Bioactive Anthocyanins")

boxplotBias(vars = c("CA.Gluc","DHPAA","DHPAA.Gluc", "DHPAA.Gluc.Sulfate","Total.DHPAA"), 
                     table1.0 = plasmAnt, factore ="Sex", removeOutliers = F, titlePLot = "B. Sex:Time evolution Anthocyanins-Plasm",  x_label = "Bioactive Anthocyanins")

boxplotBias(vars = c("DHPAA.Gluc", "DHPAA.di.Gluc","DHPAA.Gluc.Sulfate", 
                     "VA.GG","VA.Sulfate"), 
                     table1.0 = plasmAnt, factore ="Sweetener", removeOutliers = F, titlePLot = "C. Sweetener:Time evolution Anthocyanins-Plasm",  x_label = "Bioactive Anthocyanins")




#Boxplot flavanones plasm

boxplotBias(vars = c("E", "HE.G","NG"), table1.0 = urineFlav, factore = "Time", removeOutliers = T, titlePLot = "A. Time evolution Flavanones-Plasm",  x_label = "Bioactive Flavanones")

boxplotBias(vars = c("E", "HE.G","NG"), table1.0 = urineFlav, factore = "Sex", removeOutliers = T, titlePLot = "B. Sex:Time evolution Flavanones-Plasm",  x_label = "Bioactive Flavanones")

boxplotBias(vars = c("E", "HE.G","NG"), table1.0 = urineFlav, factore = "Sweetener", removeOutliers = F, titlePLot = "C. Sweetener:Time evolution Flavanones-Plasm",  x_label = "Bioactive Flavanones")

```

# Clustering with feature selection


#### AntPlasm 

```{r clustering urineAnt}

set.seed(123)

## time initial 

# feature selection

borutaAP_I <- Boruta(Sex~ ., data = plasmAntImp %>%
                   filter(Time == "Initial") %>%
                   select(-c(grouping, numVol, Time, DHPAA.di.Sulfate, TFA.Gluc, VA, VA.Sulfate)), doTrace = 3, maxRuns = 500)

# BORUTA RESULTS:
getSelectedAttributes(borutaAP_I)
# [1] "Total.CA"      "TFA.Sulfate"   "Total.TFA"     "VA.di.Sulfate" "Total.VA"     

# clustering method selection 

  tableAP_I <-  plasmAntImp %>%
    filter(Time == "Initial") %>%
    select(getSelectedAttributes(borutaAP_I)) 
  
  comparisonAP_I <- clValid(
    obj        = tableAP_I,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonAP_I)
  
# RESULTS CLUSTERING VALIDATION: 

#              Score  Method       Clusters
# APN          0.0000 hierarchical 2       
# AD           0.1523 kmeans       6       
# ADM          0.0000 hierarchical 2       
# FOM          0.0694 kmeans       6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.7479 hierarchical 2       
# Silhouette   0.7902 hierarchical 2  
    
# CLUSTERING TECHNIQUE SELECTION: kmeans clustering, k = 6
  
  clustersAP_I <- kmeans(tableAP_I, centers = 6)
  pcaAP_I <- prcomp(tableAP_I)

p1_AP <- fviz_pca_biplot(pcaAP_I, label = c("quali", "var"), labelsize =6,  habillage = clustersAP_I$cluster, addEllipses = T, col.var = 1, title = "A. Anthocyanins in Plasm at Initial Time", arrowsize = 0.8, repel = T)

tableAP_I[81,]

# punto 81 da problemas...
  
## time final

# feature selection  
  
borutaAP_F <- Boruta(Sex:Sweetener~ ., data = plasmAntImp %>%
                   filter(Time == "Final") %>%
                   select(-c(grouping, numVol, Time, DHPAA.di.Sulfate, TFA.Gluc, VA, VA.Sulfate)), doTrace = 3, maxRuns = 500)



# BORUTA RESULTS:
getSelectedAttributes(borutaAP_F)

# [1] "DHPAA.Gluc.Sulfate" "TFA.Sulfate"        "Total.TFA"          "VA.GG"              "VA.Gluc.Sulfate"   
# "Total.VA"    

# clustering method selection 

  tableAP_F <-  plasmAntImp %>%
  filter(Time == "Final") %>%
  select(getSelectedAttributes(borutaAP_F)) 
  
  comparisonAP_F <- clValid(
    obj        = tableAP_F,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonAP_F)


# RESULTS CLUSTERING VALIDATION: 
  
#              Score  Method       Clusters
# APN          0.0106 hierarchical 2       
# AD           0.2931 clara        6       
# ADM          0.0123 hierarchical 3       
# FOM          0.1124 clara        6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.5437 hierarchical 3       
# Silhouette   0.6707 hierarchical 2       


# CLUSTERING TECHNIQUE SELECTION: clara clustering, k = 6 (clara ~ pam)
  
  clustersAP_F <-cluster::pam(x = tableAP_F, k = 6, metric = "manhattan")
  pcaAP_F <- prcomp(tableAP_F)

p2_AP <- fviz_pca_biplot(pcaAP_F, label = c("quali", "var"), labelsize =6, habillage = clustersAP_F$clustering, addEllipses = T,col.var = "black", title = "B. Anthocyanins in Plasm at Final Time", arrowsize = 0.8, repel = T)

### total boxplot
  
### initial time
  
tablaClustersAP_I <-  plasmAntImp %>% filter(Time == "Initial") %>%
                         select(-c(grouping, numVol, Time,DHPAA.di.Sulfate, TFA.Gluc, VA, VA.Sulfate)) %>%
                         add_column(clusters = clustersAP_I$cluster)

tableSexAP_I <- table(tablaClustersAP_I$Sex, tablaClustersAP_I$clusters)#tabla_clusters %>% count(Sexo, clusters)  

tablaClustersAP_I <- tablaClustersAP_I %>% select(-c(Sweetener, Sex))

longtableAP_I <- melt(tablaClustersAP_I, id = c("clusters"))

p3_AP <- ggplot(longtableAP_I, aes(factor(variable, level = unique(longtableAP_I$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
  # coord_cartesian(ylim = quantile(longtableAP_I$value, c(0, 0.97)))+
      annotation_custom(grob = tableGrob(tableSexAP_I, rows = c("M", "W"), theme = ttheme_default(base_size = 8)), 
      xmin=14,xmax=17, ymin=0.75, ymax=1)+
          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+

      ggtitle("A. Anthocyanins in Plasm at Initial Time")+
      labs(y = "Standarized Value", x = "Bioactive Anthocyanins", fill = "Cluster")



### final time

tablaClustersAP_F <-  plasmAntImp %>% filter(Time == "Final") %>%
                         select(-c(grouping, numVol, Time, DHPAA.di.Sulfate, TFA.Gluc, VA, VA.Sulfate)) %>%
                         add_column(clusters = clustersAP_F$clustering)

tableSexAP_F <- table(tablaClustersAP_F$Sex, tablaClustersAP_F$clusters) #tabla_clusters %>% count(Sexo, clusters)  
tableSweetenerAP_F <- table(tablaClustersAP_F$Sweetener, tablaClustersAP_F$clusters) #tabla_clusters %>% count(Endulzante, clusters)

tablaClustersAP_F <- tablaClustersAP_F %>% select(-c(Sweetener, Sex))

longtableFn <- melt(tablaClustersAP_F, id = c("clusters"))

p4_AP <- ggplot(longtableFn, aes(factor(variable, level = unique(longtableFn$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
  # coord_cartesian(ylim = quantile(longtableFn$value, c(0, 0.97)))+
  annotation_custom(grob = tableGrob(tableSexAP_F, rows = c("M", "W"), theme = ttheme_default(base_size = 8)), 
                    xmin= 13,xmax=16, ymin=0.95, ymax=1.15)+
  annotation_custom(grob = tableGrob(tableSweetenerAP_F, rows=c("SA", "ST","SU"), theme = ttheme_default(base_size = 8)), 
                    xmin= 13,xmax=16, ymin=0.75, ymax=0.95)+
          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+

      ggtitle("B. Anthocyanins in Plasm at Final Time")+
      labs(y = "Standarized Value", x = "Bioactive Anthocyanins", fill = "Cluster")
  

# plotting in da block

ggarrange(p1_AP,p2_AP)
ggarrange(p3_AP,p4_AP)
        
```


#### AntUrine

```{r clustering urineAnt}

set.seed(123)


### urineFlav

## time initial 

# feature selection

borutaAU_I <- Boruta(Sex:Sweetener~ ., data = urineAntImp %>%
                   filter(Time == "Initial") %>%
                   select(-c(grouping, numVol, Time, CA.Sulfate, DHPAA.di.Gluc, TFA.di.sulfate.1, TIFA.Sulfate.1)), doTrace = 3, maxRuns = 500)

# BORUTA RESULTS:
getSelectedAttributes(borutaAU_I)
# [1] "CA.Gluc"          "CA.Gluc.Sulfate"  "DHPAA.di.Sulfate" "VA"              
# [5] "Total.VA" 

# clustering method selection 

  tableAU_I <-  urineAntImp %>%
    filter(Time == "Initial") %>%
    select(getSelectedAttributes(borutaAU_I)) 
  
  comparisonTI <- clValid(
    obj        = tableAU_I,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonTI)

# RESULTS CLUSTERING VALIDATION: 
  
#              Score  Method       Clusters
# APN          0.0031 kmeans       2       
# AD           0.0821 pam          6       
# ADM          0.0129 hierarchical 2       
# FOM          0.0564 clara        6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.7206 hierarchical 2       
# Silhouette   0.8466 hierarchical 3       
    
# CLUSTERING TECHNIQUE SELECTION: pam clustering k = 6
  
  
  clustersAU_I <- cluster::pam(tableAU_I, k = 6, metric = "manhattan")
  pcaAU_I <- prcomp(tableAU_I)


  
  p1_AU_I <- fviz_pca_biplot(pcaAU_I, label = c("quali", "var"), labelsize = 6, habillage = clustersAU_I$clustering,
                            addEllipses = T,col.var = "black", title = "A. Anthocyanins in Urine at Initial Time",
                             arrowsize = 0.8, repel = T)

## time final 

# feature selection  
  
borutaF <- Boruta(Sex:Sweetener~ ., data = urineAntImp %>%
                   filter(Time == "Final") %>%
                   select(-c(grouping, numVol, Time, CA.Sulfate, DHPAA.di.Gluc, TFA.di.sulfate.1, TIFA.Sulfate.1)), doTrace = 2, maxRuns = 500)

# [1] "CA"       "Total.CA" "DHPAA"    "TFA.Gluc"
getSelectedAttributes(borutaF)

  tableFn <-  urineAntImp %>%
  filter(Time == "Final") %>%
  select(getSelectedAttributes(borutaF)) 
  
  comparisonTI <- clValid(
    obj        = tableFn,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonTF)
  
# RESULTS CLUSTERING VALIDATION: 

#              Score  Method       Clusters
# APN          0.0013 hierarchical 2       
# AD           0.2944 pam          6       
# ADM          0.0024 hierarchical 2       
# FOM          0.0834 som          6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.6514 hierarchical 2       
# Silhouette   0.6364 hierarchical 2  

# CLUSTERING TECHNIQUE SELECTION: pam clustering k = 6
  
  clustersFn <-cluster::pam(x = tableFn, k = 6, metric = "manhattan")
  pcaFn <- prcomp(tableFn)

  p2 <- fviz_pca_biplot(pcaFn, label = c("quali", "var"), labelsize = 6, habillage = clustersFn$clustering, 
                        addEllipses = T,col.var = "black", arrowsize = 0.8, repel = T,
                        title = "B. Anthocyanins in Urine at Final Time")



### total boxplot
  
### initial time
  
tablaClustersIn <-  urineAntImp %>% filter(Time == "Initial") %>%
                         select(-c(grouping, numVol, Time, CA.Sulfate, DHPAA.di.Gluc,
                                   TFA.di.sulfate.1, TIFA.Sulfate.1)) %>%
                         add_column(clusters = clustersAU_I$clustering)

tableSexIn <- table(tablaClustersIn$Sex, tablaClustersIn$clusters)#tabla_clusters %>% count(Sexo, clusters)  

tablaClustersIn <- tablaClustersIn %>% select(-c(Sweetener, Sex))

longtableIn <- melt(tablaClustersIn, id = c("clusters"))

p3 <- ggplot(longtableIn, aes(factor(variable, level = unique(longtableIn$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
  coord_cartesian(ylim = quantile(longtableIn$value, c(0, 0.97)))+
      annotation_custom(grob = tableGrob(tableSexIn, rows = c("M", "W"), theme = ttheme_default(base_size = 8)), 
      xmin=16,xmax=19, ymin=0.4, ymax=0.5)+
          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+

      ggtitle("A. Anthocyanins in Urine at Initial Time")+
      labs(y = "Standarized Value", x = "Bioactive Anthocyanins", fill = "Cluster")

# final time

tablaClustersFn <-  urineAntImp %>% filter(Time == "Final")%>%
                         select(-c(grouping, numVol, Time, CA.Sulfate, DHPAA.di.Gluc, TFA.di.sulfate.1, TIFA.Sulfate.1)) %>%
                         add_column(clusters = clustersFn$clustering)

tableSexFn <- table(tablaClustersFn$Sex, tablaClustersFn$clusters) #tabla_clusters %>% count(Sexo, clusters)  
tableSweetenerFn <- table(tablaClustersFn$Sweetener, tablaClustersFn$clusters) #tabla_clusters %>% count(Endulzante, clusters)

tablaClustersFn <- tablaClustersFn %>% select(-c(Sweetener, Sex))

longtableFn <- melt(tablaClustersFn, id = c("clusters"))

p4 <- ggplot(longtableFn, aes(factor(variable, level = unique(longtableFn$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
  coord_cartesian(ylim = quantile(longtableFn$value, c(0, 0.97)))+
  annotation_custom(grob = tableGrob(tableSexFn, rows = c("M", "W"), theme = ttheme_default(base_size = 6)), 
                    xmin= 16,xmax=19, ymin=0.45, ymax=0.54)+
  annotation_custom(grob = tableGrob(tableSweetenerFn, rows=c("SA", "ST","SU"), theme = ttheme_default(base_size = 6)), 
                    xmin= 16,xmax=19, ymin=0.35, ymax=0.45)+
          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+

      ggtitle("B. Anthocyanins in urine at Final Time")+
      labs(y = "Standarized Value", x = "Bioactive Anthocyanins", fill = "Cluster")
  

# plotting in da block

ggarrange(p1_AU_I,p2)
ggarrange(p3,p4)
        
```


#### FlavPlasm

```{r clustering urineFlav}

set.seed(123)

## time initial 

# feature selection

borutaFP_I <- Boruta(Sex~ ., data = plasmFlavImp %>%
                   filter(Time == "Initial") %>%
                   select(-c(grouping, numVol, Time,Total.E)), doTrace = 2, maxRuns = 500)

# BORA RESULTS:
# [1]  "ES" -> we ignore boruta lol

# clustering method selection 

  tableFP_I <-  plasmFlavImp %>%
    filter(Time == "Initial")  %>%
    select(c(E, E.S, HE.G, N.G))

  comparisonFP_I <- clValid(
    obj        = tableFP_I,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonFP_I)
  
# RESULTS CLUSTERING VALIDATION: 
    
#              Score  Method       Clusters
# APN          0.0293 hierarchical 3       
# AD           0.1449 pam          5       
# ADM          0.0262 model        2       
# FOM          0.0749 model        2       
# Connectivity 3.5190 sota         2       
# Dunn         0.2542 kmeans       5       
# Silhouette   0.5269 hierarchical 2        
  
  
# CLUSTERING TECHNIQUE SELECTION: model based clustering k = 2
  
  
  clustersFP_I <- Mclust(tableFP_I, G= 4)
  
  pcaFP_I <- prcomp(tableFP_I)

p1_FP <- fviz_pca_biplot(pcaFP_I, label = c("quali", "var"), labelsize =6, habillage = clustersFP_I$classification, addEllipses = T, col.var = "black",
title = "A. Flavanones in Plasm at Initial Time", arrowsize =0.8,repel = T)

  
## time final

# feature selection  
  
  borutaFP_F <- Boruta(Sex~ ., data = plasmFlavImp %>%
                   filter(Time == "Final") %>%
                   select(-c(grouping, numVol, Time,Total.E)), doTrace = 2, maxRuns = 500)

# BORA RESULTS:
# [1]  "E" -> we ignore boruta lol

# clustering method selection 

  tableFP_F <-  plasmFlavImp %>%
    filter(Time == "Final")  %>%
    select(c(E, E.S, HE.G, N.G))
  
  comparisonFP_F <- clValid(
    obj        = tableFP_F,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonFP_F)

# RESULTS CLUSTERING VALIDATION: 

#              Score  Method       Clusters
# APN          0.0000 hierarchical 2       
# AD           0.1741 diana        6       
# ADM          0.0000 hierarchical 2       
# FOM          0.0914 diana        4       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.9959 hierarchical 2       
# Silhouette   0.8013 hierarchical 2  

# CLUSTERING TECHNIQUE SELECTION:  diana clustering k = 4
  
  distancesFP_F <- dist(tableFP_F[-c(55, 105),], method = "manhattan")
  
  dianaFP_F <- diana(distancesFP_F, diss = T, metric = "manhattan")
  
  clustersFP_F <- cutree(dianaFP_F, k = 4)
  
  pcaFP_F <- prcomp(tableFP_F[-c(55, 105),])

p2_FP <- fviz_pca_biplot(pcaFP_F, habillage = clustersFP_F, addEllipses = T,col.var = "black", title = "B. Flavanones in Plasm at Final Time",label = c("quali", "var"), labelsize =6, arrowsize = 0.8, repel = T)

##### TAKE CARE ABOUT 55 AND 105 POINTS  

  
    
### total boxplot ----
  
### initial time
  
tablaClustersFP_I <-  plasmFlavImp %>% filter(Time == "Initial")
                         select(-c(grouping, numVol, Time, Total.E)) %>%
                         add_column(clusters = clustersFP_I$classification)

tableSexFP_I <- table(tablaClustersFP_I$Sex, tablaClustersFP_I$clusters)#tabla_clusters %>% count(Sexo, clusters)  

tablaClustersFP_I <- tablaClustersFP_I %>% select(-c(Sweetener, Sex))

longtableFP_I <- melt(tablaClustersFP_I, id = c("clusters"))

p3_FP <- ggplot(longtableFP_I, aes(factor(variable, level = unique(longtableFP_I$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
      annotation_custom(grob = tableGrob(tableSexFP_I, rows = c("M", "W"), theme = ttheme_default(base_size = 8)), 
      xmin= 3,xmax=6, ymin=0.75, ymax=1.25)+
      ggtitle("A. Flavanones in Plasm at Initial Time")+
      labs(y = "Standarized Value", x = "Bioactive Flavanones", fill = "Cluster")

# final time

tablaClustersFP_F <-  plasmFlavImp %>% filter(Time == "Final") %>% filter(!row_number() %in% c(55,105)) %>% 
                         select(-c(grouping, numVol, Time, Total.E)) %>%
                         add_column(clusters = clustersFP_F)

tableSexFP_F <- table(tablaClustersFP_F$Sex, tablaClustersFP_F$clusters) #tabla_clusters %>% count(Sexo, clusters)  
tableSweetenerFP_F <- table(tablaClustersFP_F$Sweetener, tablaClustersFP_F$clusters) #tabla_clusters %>% count(Endulzante, clusters)

tablaClustersFP_F <- tablaClustersFP_F %>% select(-c(Sweetener, Sex))

longtableFP_F <- melt(tablaClustersFP_F, id = c("clusters"))

p4_FP <- ggplot(longtableFP_F, aes(factor(variable, level = unique(longtableFP_F$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
  annotation_custom(grob = tableGrob(tableSexFP_F, rows = c("M", "W"), theme = ttheme_default(base_size = 8)), 
                    xmin= 3,xmax=6, ymin=0.75, ymax=1)+
  annotation_custom(grob = tableGrob(tableSweetenerFP_F, rows=c("SA", "ST","SU"), theme = ttheme_default(base_size = 8)), 
                    xmin= 3,xmax=6, ymin=0.57, ymax=0.75)+
      ggtitle("B. Flavanones in Plasm at Final Time")+
      labs(y = "Standarized Value", x = "Bioactive Flavanones", fill = "Cluster")

# plotting in da block

ggarrange(p1_FP,p2_FP)
ggarrange(p3_FP,p4_FP)
        
```

#### FlavUrine

```{r clustering urineFlav}

set.seed(123)


### urineFlav

## time initial 

# feature selection

borutaI <- Boruta(Sex~ ., data = urineFlavImp %>%
                   filter(Time == "Initial") %>%
                   select(-c(grouping, numVol, Time)), doTrace = 2, maxRuns = 500)

getSelectedAttributes(borutaI)
# clustering method selection 

  tableIn <-  urineFlavImp %>%
    filter(Time == "Initial")  %>%
    select(getSelectedAttributes(borutaI))

  comparisonTI <- clValid(
    obj        = tableIn,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonTI)
  
#              Score  Method       Clusters
# APN          0.0000 hierarchical 2       
# AD           0.0674 som          6       
# ADM          0.0000 hierarchical 2       
# FOM          0.0388 hierarchical 6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         3.2955 hierarchical 2       
# Silhouette   0.9376 hierarchical 2  
  
# hierarchical k = 6

summary(comparisonTI)


library(kohonen)

som_grid <- somgrid(xdim = 25, ydim=5, topo="hexagonal")
# Finally, train the SOM, options for the number of iterations,
# the learning rates, and the neighbourhood are available
som_model <- som(as.matrix(tableIn), 
        grid=som_grid, 
        rlen=100, 
        alpha=c(0.05,0.01), 
        keep.data = TRUE)

som_cluster <- cutree(hclust(dist(som_model$codes[[1]])), k = 6)

pcaFinal <- prcomp(tableIn)

fviz_pca_biplot(pcaFinal, habillage = som_cluster)


p1 <- fviz_pca_biplot(pcaFinal, habillage = som_cluster, addEllipses = T,col.var = "black", title = "A. Flavanones in Urine at Initial Time",label = c("quali", "var"), labelsize =6, arrowsize = 0.8, repel = T)


## time final

# feature selection  
  
  borutaF <- Boruta(Sex:Sweetener~ ., data = urineFlavImp %>%
                   filter(Time == "Final") %>%
                   select(-c(grouping, numVol, Time)), doTrace = 2, maxRuns = 500)

  getSelectedAttributes(borutaF)

  tableFn <-  urineFlavImp %>%
  filter(Time == "Final") %>%
  select(getSelectedAttributes(borutaF)) 
  
  comparisonTF <- clValid(
    obj        = tableFn,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  summary(comparisonTF)
#   
#              Score  Method       Clusters
# APN          0.0063 hierarchical 2       
# AD           0.1348 diana        6       
# ADM          0.0036 hierarchical 2       
# FOM          0.0609 diana        6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.5707 hierarchical 2       
# Silhouette   0.7246 hierarchical 2    

# pam clustering k = 6
  
  
distances <- dist(tableFn, method = "manhattan")

hc_diana <- diana(x = distances, metric = "manhattan")

clusters_initial <- cutree (hc_diana, k = 6)

pca_initial <- prcomp(tableFn)

fviz_pca_biplot(pca_initial, habillage = clusters_initial)
  
p2 <- fviz_pca_biplot(pca_initial, habillage = clusters_initial, addEllipses = T,col.var = "black", title = "A. Flavanones in Urine at Final Time",label = c("quali", "var"), labelsize =6, arrowsize = 0.8, repel = T)
### total boxplot
  
### initial time
  
tablaClustersIn <-  urineFlavImp %>% filter(Time =="Initial")%>%
                         select(-c(grouping, numVol, Time)) %>%
                         filter(!row_number() == 63) %>%
                         add_column(clusters = clustersIn$clustering)

tableSexIn <- table(tablaClustersIn$Sex, tablaClustersIn$clusters)#tabla_clusters %>% count(Sexo, clusters)  

tablaClustersIn <- tablaClustersIn %>% select(-c(Sweetener, Sex))

longtableIn <- melt(tablaClustersIn, id = c("clusters"))

p3 <- ggplot(longtableIn, aes(factor(variable, level = unique(longtableIn$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
      annotation_custom(grob = tableGrob(tableSexIn, rows = c("M", "W"), theme = ttheme_default(base_size = 8)), 
      xmin= 9,xmax=13, ymin=0.75, ymax=1.25)+
      ggtitle("A. Flavanones in urine at Initial Time")+
      labs(y = "Standarized Value", x = "Bioactive Flavanones", fill = "Cluster")

# final time

tablaClustersFn <-  urineFlavImp %>% filter(Time == "Final")%>%
                         select(-c(grouping, numVol, Time)) %>%
                         add_column(clusters = clustersFn$clustering)

tableSexFn <- table(tablaClustersFn$Sex, tablaClustersFn$clusters) #tabla_clusters %>% count(Sexo, clusters)  
tableSweetenerFn <- table(tablaClustersFn$Sweetener, tablaClustersFn$clusters) #tabla_clusters %>% count(Endulzante, clusters)

tablaClustersFn <- tablaClustersFn %>% select(-c(Sweetener, Sex))

longtableFn <- melt(tablaClustersFn, id = c("clusters"))

p4 <- ggplot(longtableFn, aes(factor(variable, level = unique(longtableFn$variable)),as.numeric(value), 
                            fill=factor(clusters)))+ geom_boxplot()+
  annotation_custom(grob = tableGrob(tableSexFn, rows = c("M", "W"), theme = ttheme_default(base_size = 8)), 
                    xmin= 9,xmax=14, ymin=0.75, ymax=1.25)+
  annotation_custom(grob = tableGrob(tableSweetenerFn, rows=c("SA", "ST","SU"), theme = ttheme_default(base_size = 8)), 
                    xmin= 9,xmax=14, ymin=0.70, ymax=0.80)+
      ggtitle("B. Flavanones in urine at Final Time")+
      labs(y = "Standarized Value", x = "Bioactive Flavanones", fill = "Cluster")

# plotting in da block

ggarrange(p1,p2)
ggarrange(p3,p4)
        
```


# Power calculations for ANOVA

```{r power}

library(Superpower)

plasmAntImp

ANOVA_design(design = )



```
























# Clustering w/O feature selection

```{r clustering}
clusteringTest <- function(pathToTable, fakepath){

  table1.4 <- main1prepoc(pathToTable, fakepath)

  table1.5_initial <-  table1.4 %>%
    filter(Time == "Initial") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time)) %>%
    mutate_if(is.double,as.numeric) #%>% drop_na()

  table1.5_final <-  table1.4 %>%
    filter(Time == "Final") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time)) %>%
    mutate_if(is.double,as.numeric) #%>% drop_na()

  comparisonTI <- clValid(
    obj        = table1.5_initial,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )
  comparisonTF <- clValid(
    obj        = table1.5_final,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

  return(list(comparisonTI, comparisonTF))
}
#   
#   # ### model-based clustering
#   # 
#   # # Initial time
#   # model_clustering_OF <- Mclust(table1.5_initial)
#   # 
#   # p1I <- fviz_mclust(object = model_clustering_OF, what = "BIC", pallete = "jco",
#   #                   title = paste("Model Selection ", pathToTable, "Initial Time")) + scale_x_discrete(limits = c(1:10))
#   # p2I <- fviz_mclust(model_clustering_OF, what = "classification", geom = "point",
#   #                   title = paste("Clusters Plot ", pathToTable, "Initial Time") , pallete = "jco")
#   # 
#   # # Final time
#   # 
#   # model_clustering_OF <- Mclust(table1.5_final)
#   # 
#   # p1F <- fviz_mclust(object = model_clustering_OF, what = "BIC", pallete = "jco",
#   #                   title = paste("Model Selection ", pathToTable, "Final Time")) + scale_x_discrete(limits = c(1:10))
#   # p2F <- fviz_mclust(model_clustering_OF, what = "classification", geom = "point",
#   #                   title = paste("Clusters Plot ", pathToTable, "Final Time"), pallete = "jco")
#   # 
#   # return(list(comparisonTI, comparisonTF, p1I, p2I, p1F, p2F))
# }
# 

```

#### Plasm flavanones set

```{r plasm flav analysis clustering}

plasmFlav <- main1prepoc("../../effectsSexIntakers/data/chronicPlasmFlav.csv", "data/chronicPlasmFlav.csv")

sapply(plasmFlav, function(x) sum(is.na(x)))

#too much NA in Total.E

plasmFlavImp <- impute_cart(plasmFlav, E+E.S ~ Sweetener + Sex + Time+ HE.G + N.G)

  table1.5_initial <-  plasmFlavImp %>%
    filter(Time == "Initial") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, Total.E)) %>%
    mutate_if(is.double,as.numeric) #%>% drop_na()

  table1.5_final <-  plasmFlavImp %>%
    filter(Time == "Final") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, Total.E)) %>%
    mutate_if(is.double,as.numeric)

  comparisonTI <- clValid(
    obj        = table1.5_initial,
    nClust     = 2:9,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )
  comparisonTF <- clValid(
    obj        = table1.5_final,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

summary(comparisonTI)

#              Score  Method       Clusters
# APN          0.0293 hierarchical 3       
# AD           0.1431 som          6       
# ADM          0.0262 model        2       
# FOM          0.0749 model        2       
# Connectivity 3.5190 sota         2       
# Dunn         0.2542 kmeans       5       
# Silhouette   0.5269 hierarchical 2 

### model-based clustering

# Initial time

model_clustering_OF <- Mclust(table1.5_initial, G = 3)

p1I <- fviz_mclust(object = model_clustering_OF, what = "BIC", pallete = "jco",
                  title = paste("Model Selection  Plasm Flavanones Initial Time")) + scale_x_discrete(limits = c(1:10))
p2I <- fviz_mclust(model_clustering_OF, what = "classification", geom = "point",
                  title = paste("Clusters Plot  Plasm Flavanones Initial Time") , pallete = "jco")

plasmFlavClust <- cbind(table1.5_initial, model_clustering_OF$classification)

pcaPF <- prcomp(table1.5_initial, scale = T)

fviz_pca_biplot(pcaPF, habillage = model_clustering_OF$classification)

ggarrange(p1I, p2I)


# Final time

#              Score  Method       Clusters
# APN          0.0000 hierarchical 2       
# AD           0.1741 diana        6       
# ADM          0.0000 hierarchical 2       
# FOM          0.0914 diana        4       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.9959 hierarchical 2       
# Silhouette   0.8013 hierarchical 2 

# diana clustering

summary(comparisonTF)

distances <- dist(x = table1.5_final[-c(55,105),], method = "manhattan")

hc_diana <- diana(x = distances, diss = TRUE, metric = "manhattan")

fviz_dend(hc_diana, k = 4)

clusters_final <- cutree(tree = hc_diana, k = 4)

pcaFinal <- prcomp(table1.5_final[-c(55,105),], scale = T)

fviz_pca_biplot(pcaFinal, habillage = clusters_final)



```

#### Plasm Anthocyanins set

```{r}

plasmAnt <- main1prepoc("../../effectsSexIntakers/data/chronicPlasmAnt.csv", "data/chronicPlasmAnt.csv")

sapply(plasmAnt, function(x) sum(is.na(x)))

# We impute CA, CA.Gluc, CA.Sulfate, DHPAA.Gluc, DHPAA.di.Gluc, DHPAA.Gluc.Sulfate, TFA.Sulfate, VA.Gluc.Sulfate, Va.di
# sulfate
# We remove DHPAA.di.Sulfate, TFA.Gluc, VA, VA.Sulfate, 

plasmAntImp <- impute_cart(dat = plasmAnt, formula = CA+ CA.G+ CA.S+ DHPAA.G+ DHPAA.GG+ DHPAA.GS + TFA.S+ VA.GG+ VA.SS ~ Sweetener + Sex + Time + Total.CA + DHPAA+Total.DHPAA+ Total.TFA+VA.GG+ Total.VA)

  table1.5_initial <-  plasmAntImp %>%
    filter(Time == "Initial") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, DHPAA.di.Sulfate, TFA.Gluc, VA, VA.Sulfate)) %>%
    mutate_if(is.double,as.numeric) #%>% drop_na()

  table1.5_final <-  plasmAntImp %>%
    filter(Time == "Final") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, DHPAA.di.Sulfate, TFA.Gluc, VA, VA.Sulfate)) %>%
    mutate_if(is.double,as.numeric)

  comparisonTI <- clValid(
    obj        = table1.5_initial,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )
  comparisonTF <- clValid(
    obj        = table1.5_final,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

summary(comparisonTI)

#              Score  Method       Clusters
# APN          0.0000 hierarchical 3       
# AD           0.4898 pam          6       
# ADM          0.0000 hierarchical 3       
# FOM          0.1031 hierarchical 5       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.6871 hierarchical 2       
# Silhouette   0.6062 hierarchical 2

# hierarchical cluster k = 5

distances <- dist(x = table1.5_initial, method = "manhattan")

hc_hier <- hclust(d = distances, method = "complete")

fviz_dend(hc_hier, k = 5)

clusters_final <- cutree(tree = hc_hier, k = 5)

pcaFinal <- prcomp(table1.5_final, scale = T)

fviz_pca_biplot(pcaFinal, habillage = clusters_final) 

summary(comparisonTF)

#              Score  Method       Clusters
# APN          0.0053 hierarchical 2       
# AD           0.6947 kmeans       6       
# ADM          0.0097 hierarchical 2       
# FOM          0.1448 model        6       
# Connectivity 3.0718 hierarchical 2       
# Dunn         0.4619 hierarchical 2       
# Silhouette   0.5005 hierarchical 2 

# model k = 6

model_clustering_TF <- Mclust(table1.5_initial, G = 6)

p1I <- fviz_mclust(object = model_clustering_TF, what = "BIC", pallete = "jco",
                  title = paste("Model Selection  Plasm Flavanones Initial Time")) + scale_x_discrete(limits = c(1:10))
p2I <- fviz_mclust(model_clustering_TF, what = "classification", geom = "point",
                  title = paste("Clusters Plot  Plasm Flavanones Initial Time") , pallete = "jco")

pcaPF <- prcomp(table1.5_initial, scale = T)

fviz_pca_biplot(pcaPF, habillage = model_clustering_TF$classification, addEllipses = T)


```

#### Urine Anthocyanins set

```{r}
urineAnt <- main1prepoc("../../effectsSexIntakers/data/chronicUrineAnt.csv", "data/chronicUrineAnt.csv")


sapply(urineAnt, function(x) sum(is.na(x)))

# We impute CA+ CA.Gluc+ DHPAA+ DHPAA.Gluc+DHPAA.Gluc.Sulfate+DHPAA.di.Sulfate+Total.DHPAA+TFA.Gluc+ TFA.Sulfate+ VA+ VA.GG +  VA.Gluc.Sulfate+ Va.di.Sulfate
# sulfate
# We remove CA.Sulfate, DHPAA.di.Gluc, TFA.di.Sulfate, TIFA.Sulfate.1 VA, VA.Sulfate, 

urineAnt$Total.CA <- as.numeric(urineAnt$Total.CA)
urineAnt$CA.Gluc.Sulfate <- as.numeric(urineAnt$CA.Gluc.Sulfate)

sapply(urineAntImp, function(x) sum(is.na(x)))


urineAntImp <- impute_cart(dat = urineAnt, formula = CA + CA.Gluc + CA.Gluc.Sulfate+ Total.CA+ DHPAA+ DHPAA.Gluc + DHPAA.Gluc.Sulfate + DHPAA.di.Sulfate + Total.DHPAA + TFA.Gluc + TFA.Sulfate+ VA+ VA.GG +  VA.Gluc.Sulfate+ VA.di.Sulfate
                           ~ Sweetener + Sex + Time + Total.TFA + Total.VA)

  table1.5_initial <-  urineAntImp %>%
    filter(Time == "Initial") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, CA.Sulfate, DHPAA.di.Gluc, TFA.di.sulfate.1, TIFA.Sulfate.1)) %>%
    mutate_if(is.character,as.numeric) #%>% drop_na()

  table1.5_final <-  urineAntImp %>%
    filter(Time == "Final") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, CA.Sulfate, DHPAA.di.Gluc, TFA.di.sulfate.1, TIFA.Sulfate.1)) %>%
    mutate_if(is.character,as.numeric)

  comparisonTI <- clValid(
    obj        = table1.5_initial,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )
  comparisonTF <- clValid(
    obj        = table1.5_final,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )


summary(comparisonTI)

#              Score  Method       Clusters
# APN          0.0022 hierarchical 3       
# AD           0.4889 pam          6       
# ADM          0.0135 hierarchical 2       
# FOM          0.1008 diana        6       
# Connectivity 4.9087 hierarchical 2       
# Dunn         0.6936 hierarchical 5       
# Silhouette   0.7852 hierarchical 2       

# diana k = 6 

distances <- dist(table1.5_initial, method = "manhattan")

hc_diana <- diana(x = distances, metric = "manhattan")

clusters_initial <- cutree (hc_diana, k = 6)

pca_initial <- prcomp(table1.5_initial, scale = T)

fviz_pca_biplot(pca_initial, habillage = clusters_initial)


summary(comparisonTF)


#              Score  Method       Clusters
# APN          0.0019 hierarchical 5       
# AD           0.4652 kmeans       6       
# ADM          0.0070 hierarchical 2       
# FOM          0.0918 kmeans       6       
# Connectivity 5.1798 hierarchical 2       
# Dunn         0.3797 hierarchical 4       
# Silhouette   0.6283 hierarchical 2 

# k-means k = 6

clusters_final <- kmeans(x = table1.5_final, centers = 6)

pcaFinal <- prcomp(table1.5_final, scale = T)

fviz_pca_biplot(pcaFinal, habillage = clusters_final$cluster)


```

#### Urine Flavanones Set

```{r}

urineFlav <- main1prepoc("../../effectsSexIntakers/data/chronicUrineFlav.csv", "data/chronicUrineFlav.csv")

sapply(urineFlav, function(x) sum(is.na(x)))

# We impute E + EG + ES + HE.G + N + NG + NGG + NS
# We remove nothing
# We use as predictors Total.E + HE + HE.GG + Total.HE + Total.N

urineFlavImp <- impute_cart(urineFlav, E + EG.1 + ES + HE.G + N + NG + NGG + NS ~ Sweetener + Sex + Time + Total.E + HE + HE.GG + Total.HE + Total.N)

  table1.5_initial <-  urineFlavImp %>%
    filter(Time == "Initial") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, Total.E)) %>%
    mutate_if(is.double,as.numeric) #%>% drop_na()

  table1.5_final <-  urineFlavImp %>%
    filter(Time == "Final") %>%
    select(-c(grouping, Sweetener, Sex, numVol, Time, Total.E)) %>%
    mutate_if(is.double,as.numeric)

  comparisonTI <- clValid(
    obj        = table1.5_initial,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )
  comparisonTF <- clValid(
    obj        = table1.5_final,
    nClust     = 2:6,
    clMethods  = c( "hierarchical", "kmeans", "diana", "fanny", "som", "model", "sota", "pam", "clara","agnes"),
    validation = c("stability", "internal")
  )

summary(comparisonTI)

#              Score  Method       Clusters
# APN          0.0000 hierarchical 2       
# AD           0.2416 pam          6       
# ADM          0.0000 hierarchical 2       
# FOM          0.0650 kmeans       6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         1.4836 hierarchical 2       
# Silhouette   0.8408 hierarchical 2

# kmeans k = 6

clusters_initial <- kmeans(x = table1.5_initial, centers = 6)

pca_initial <- prcomp(table1.5_initial, scale = T)

fviz_pca_biplot(pca_initial, habillage = clusters_initial$cluster)

# Time  = final model

summary(comparisonTF)

#              Score  Method       Clusters
# APN          0.0013 hierarchical 2       
# AD           0.2944 pam          6       
# ADM          0.0024 hierarchical 2       
# FOM          0.0834 som          6       
# Connectivity 2.9290 hierarchical 2       
# Dunn         0.6514 hierarchical 2       
# Silhouette   0.6364 hierarchical 2  

# som clustering k = 6

library(kohonen)

som_grid <- somgrid(xdim = 25, ydim=5, topo="hexagonal")
# Finally, train the SOM, options for the number of iterations,
# the learning rates, and the neighbourhood are available
som_model <- som(as.matrix(table1.5_final), 
        grid=som_grid, 
        rlen=100, 
        alpha=c(0.05,0.01), 
        keep.data = TRUE)

som_cluster <- cutree(hclust(dist(som_model$codes[[1]])), k = 6)

pcaFinal <- prcomp(table1.5_final, scale = T)

fviz_pca_biplot(pcaFinal, habillage = som_cluster)

```
